import { iconWithClassName } from "@/utils/iconWithClassName";
import {
  AlertTriangle,
  BellRing,
  Check,
  ChevronLeft,
  Home,
  Info,
  MessageCircle,
  MoonStar,
  Pencil,
  Plus,
  Search,
  Settings,
  Star,
  Sun,
  Tags,
  Terminal,
  User,
  X,
} from "lucide-react-native";
iconWithClassName(Info);
iconWithClassName(MoonStar);
iconWithClassName(Sun);
iconWithClassName(Home);
iconWithClassName(Search);
iconWithClassName(User);
iconWithClassName(ChevronLeft);
iconWithClassName(Settings);
iconWithClassName(Pencil);
iconWithClassName(MessageCircle);
iconWithClassName(Terminal);
iconWithClassName(AlertTriangle);
iconWithClassName(X);
iconWithClassName(Check);
iconWithClassName(BellRing);
iconWithClassName(Plus);
iconWithClassName(Tags);
iconWithClassName(Star);
export {
  AlertTriangle,
  BellRing,
  Check,
  ChevronLeft,
  Home,
  Info,
  MessageCircle,
  MoonStar,
  Pencil,
  Plus,
  Search,
  Settings,
  Star,
  Sun,
  Tags,
  Terminal,
  User,
  X,
};
